### ISSUE TITLE
🐛 Bug Report: Problems with husky on windows

### ISSUE THREAD

**Issue by EmmaDawsonDev** [novuhq/novu#1408]
### 📜 Description

I tried to make a small change and when I tried to commit my changes I got the following errors:

First I got a windows script telling me that a file contained an invalid character code 800A03F6

Then husky failed to commit with the following message: ```Oops! Something went wrong! :(

ESLint: 8.23.0

Error: Cannot read config file: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace.js
Error: Command failed: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace-async.js
Referenced from: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\.eslintrc.js
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace.js:54:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Object.module.exports [as default] (C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\import-fresh\index.js:32:59)
husky - pre-commit hook exited with code 1 (error)```

The commit message was formatted as a conventional commit.

This is happening on windows 11, using VSCode.

### 👟 Reproduction steps

Removed outline-none class from button.jsx, added *:focus-visible styles to global css file. Then tried to commit.

### 👍 Expected behavior

It should commit.

### 👎 Actual Behavior with Screenshots

Oops! Something went wrong! :(

ESLint: 8.23.0

Error: Cannot read config file: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace.js
Error: Command failed: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace-async.js
Referenced from: C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\.eslintrc.js
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\eslint-config-airbnb\whitespace.js:54:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Object.module.exports [as default] (C:\Users\squig\Documents\Hacktober\2022\hacksquad-website\node_modules\import-fresh\index.js:32:59)
husky - pre-commit hook exited with code 1 (error)

### 💻 Operating system

Windows

### 🤖 Node Version

16.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@EmmaDawsonDev seems that the issue your having is with hacksquad project right? I will move it to the appropriate repository.
