### ISSUE TITLE
🐛 Bug Report: Cannot assign to read only property 'unseenBadgeBackgroundColor' of object '#<Object>'

### ISSUE THREAD

**Issue by hckhanh** [novuhq/novu#2004]
### 📜 Description

Integrate with built-in notification-center. I am using Vite

### 👟 Reproduction steps

Click on the bell

### 👍 Expected behavior

Notification popup appeared

### 👎 Actual Behavior with Screenshots

It crashed

### 💻 Operating system

Windows

### 🤖 Node Version

18.12.1

### 📃 Provide any additional context for the Bug.

```
Cannot assign to read only property 'unseenBadgeBackgroundColor' of object '#<Object>'
    at baseAssignValue (index.js:811:12)
    at assignMergeValue (index.js:753:5)
    at index.js:933:7
    at index.js:1193:11
    at baseMerge (index.js:920:3)
    at index.js:1912:3
    at index.js:1170:9
    at apply (index.js:136:25)
    at index.js:1406:12
    at be2 (use-default-theme.hook.ts:45:9)
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by sofferjacob** [comment]
Same issue here. Created a PR with a fix
