### ISSUE TITLE
🐛 Bug Report: TypeError: o.div is not a function in Remix

### ISSUE THREAD

**Issue by rikoriswandha** [novuhq/novu#2396]
### 📜 Description

I get TypeError: o.div is not a function in Remix using the code snippets from the docs
```
import {
  NovuProvider,
  PopoverNotificationCenter,
  NotificationBell,
  IMessage,
} from '@novu/notification-center';

function Header() {
  function onNotificationClick(notification: IMessage) {
    // your logic to handle the notification click
    if (message?.cta?.data?.url) {
      window.location.href = message.cta.data.url;
    }
  }

  return (
    <NovuProvider subscriberId={'USER_ID'} applicationIdentifier={'APP_ID_FROM_ADMIN_PANEL'}>
      <PopoverNotificationCenter onNotificationClick={onNotificationClick}>
        {({ unseenCount }) => <NotificationBell unseenCount={unseenCount} />}
      </PopoverNotificationCenter>
    </NovuProvider>
  );
}
```
Is it because of React 18 or Remix using Node Stream by default?

### 👟 Reproduction steps

1. Create a new Remix App
2. Install Novu
3. Embed it into a remix page

### 👍 Expected behavior

It should render the notification bell icon

### 👎 Actual Behavior with Screenshots

TypeError: o.div is not a function
    at Object.<anonymous> (/Users/user/Development/qwork/qwork-crm-app/node_modules/@novu/notification-center/src/components/notification-center/components/layout/header/Header.tsx:99:28)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/rikoriswandha/Development/qwork/qwork-crm-app/app/components/NovuHeader/NovuHeader.tsx:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

### 🤖 Node Version

16.16.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Bhanuteja01** [comment]
Hey! I like to work with this

**Comment by jainpawan21** [comment]
Hey @Bhanuteja01 
We highly appreciate your interest in contribution, but this issue is already picked by Pawel
We have other issues opened.
Let me know if you want to work on any of them

**Comment by Bhanuteja01** [comment]
Ok happy to contribute

**Comment by LetItRock** [comment]
hey 👋 the fix will be included in the next patch release ;)
