### ISSUE TITLE
🐛 Bug Report: Main branch setup:project command failing with error

### ISSUE THREAD

**Issue by tsssdev** [novuhq/novu#2417]
### 📜 Description

Trying to setup nova project locally with this command npm run setup:project, but failing with error.

### 👟 Reproduction steps

git clone main novu branch(or cloned branch) and run: npm run setup:project

### 👍 Expected behavior

Project setup successful

### 👎 Actual Behavior with Screenshots

Getting below error and setup failing...

> setup:project
> npx --yes pnpm@7.5.0 i && node scripts/setup-env-files.js && pnpm build

Scope: all 54 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +6078
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 WARN  GET https://github.com/LetItRock/floating-vue/raw/main/packages/floating-vue/floating-vue-2.0.0-beta.21.tgz error (EPROTO). Will retry in 10 seconds. 2 retries left.
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/XX/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
 WARN  GET https://github.com/LetItRock/floating-vue/raw/main/packages/floating-vue/floating-vue-2.0.0-beta.21.tgz error (EPROTO). Will retry in 1 minute. 1 retries left.
Progress: resolved 6078, reused 5307, downloaded 0, added 6077
TypeError: Cannot set property name of  which has only a getter
    at err (/Users/XX/.npm/_npx/0437c2f26f91c49a/node_modules/pnpm/dist/pnpm.cjs:12462:20)
    at runPnpm (/Users/XX/.npm/_npx/0437c2f26f91c49a/node_modules/pnpm/dist/pnpm.cjs:192787:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/XX/.npm/_npx/0437c2f26f91c49a/node_modules/pnpm/dist/pnpm.cjs:192777:7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by tsssdev** [comment]
With help of BiswaViraj@Discord I am able to fix the issue, the problem is my  ISP has blocked the githubusercontent.com, so changed to my mibile net(Airtel) and it fixed the problem..  just for the record, in India it is failing in Jio Fibre, Act Fibre and even Jio mobile it is failing.
