### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Taha-BABI-N2NConncet** [novuhq/novu#3083]
### 📜 Description

configuring infolib sms provider and triggering an sms notification.

### 👟 Reproduction steps

=> inegration store => infolib dev (Sms) => (Set Api Key (from my account) , base Url (from my account), From (my name), set disabled to false ) => click update => trigger the notification to send SMS

### 👍 Expected behavior

return success result for sms

### 👎 Actual Behavior with Screenshots

Error 
![image](https://user-images.githubusercontent.com/124668840/227860877-e25e1630-ca62-4c88-b244-ed35c699bc54.png)

![image](https://user-images.githubusercontent.com/124668840/227861187-6e18cf6d-16a2-4a58-89dd-61d8149dcb50.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
@Taha-BABI-N2NConncet could you help with clicking on the "Show Detail" button? We might have some relevant information there to understand the actual error

**Comment by Taha-BABI-N2NConncet** [comment]
of course  

{
  "stack": "ApiException: Sms handler for provider infobip-sms is  not found\n    at SendMessageSms.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts:262:15)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/apps/api/dist/main.js:21095:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/apps/api/dist/main.js:21091:12)\n    at SendMessageSms.sendMessage (/usr/src/app/apps/api/dist/main.js:21220:16)\n    at SendMessageSms.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts:159:18)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/apps/api/dist/main.js:21092:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "response": {
    "statusCode": 400,
    "message": "Sms handler for provider infobip-sms is  not found",
    "error": "Bad Request"
  },
  "status": 400,
  "options": {},
  "message": "Sms handler for provider infobip-sms is  not found",
  "name": "ApiException"
}

![image](https://user-images.githubusercontent.com/124668840/228108326-57fb2a64-5611-427a-9cda-28de31e0bcf5.png)

**Comment by scopsy** [comment]
Okey, think I found where the error is, the provider is `infobip` in the handler but `infobip-sms` in the provider id. we should update the handler to be `infobip-sms` aswell for it.

`

export class InfobipSmsHandler extends BaseSmsHandler {
  constructor() {
    super('infobip', ChannelTypeEnum.SMS);
  }
  buildProvider(credentials: ICredentials) {
    this.provider = new InfobipSmsProvider({
      baseUrl: credentials.baseUrl,
      apiKey: credentials.apiKey,
      from: credentials.from,
    });
  }
}
`

**Comment by Taha-BABI-N2NConncet** [comment]
Thanks a lot, but can this be solved online?

**Comment by Taha-BABI-N2NConncet** [comment]
![Capture](https://user-images.githubusercontent.com/124668840/228405838-f85ad4d2-d53c-4f9b-a78e-05ebc5ab1683.PNG)

**Comment by Taha-BABI-N2NConncet** [comment]
{
  "stack": "TypeError: Cannot read properties of null (reading 'send')\n    at SendMessageSms.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts:262:39)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/apps/api/dist/main.js:21538:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/apps/api/dist/main.js:21534:12)\n    at SendMessageSms.sendMessage (/usr/src/app/apps/api/dist/main.js:21663:16)\n    at SendMessageSms.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts:159:18)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/apps/api/dist/main.js:21535:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "message": "Cannot read properties of null (reading 'send')"
}

**Comment by gitstart** [comment]
@scopsy I would like to pick this up
