### ISSUE TITLE
[NV-2149] 🐛 Bug Report: Vue component does not work if you are using `floating-vue` library

### ISSUE THREAD

**Issue by fmmattioni** [novuhq/novu#3243]
### 📜 Description

I was trying to integrate`@novu/notification-center-vue` today in a project, however I was getting this error when clicking on the notification button:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Proxy.$_computePosition (floating-vue.es.js:602:46)
    at Proxy.$_applyShow (floating-vue.es.js:743:18)
```

The notification panel wouldn't appear, and only this error was showing.

It turns out that the issue is because I am using `floating-vue` (version 2.0.0-beta.20, by the way) in my app, and novu uses its own forked version of `floating-vue` under the hood.

### 👟 Reproduction steps

1. Create a Vue 3 app;
2. Install `floating-vue`;
3. Install `@novu/notification-center-vue`;
4. Use `floating-vue` somewhere in your app;
5. Use `@novu/notification-center-vue`

### 👍 Expected behavior

When the button is clicked the notification panel should show up.

### 👎 Actual Behavior with Screenshots

The panel does not show up and get the above error message in the console.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2149](https://linear.app/novu/issue/NV-2149/🐛-bug-report-vue-component-does-not-work-if-you-are-using-floating)</sub>

**Comment by scopsy** [comment]
Not very familiar with vue regarding this, @fmmattioni is there any way we can scope our forked library in a way? So this error won't happen?
