### ISSUE TITLE
TypeError: Cannot read property 'emails' of undefined when run locally

### ISSUE THREAD

**Issue by deepaktomar47** [novuhq/novu#3373]
### Duplicates

- [ ] I have searched the existing issues

### Related page

https://docs.novu.co/community/run-locally

### Kind of issue

Unclear explanations

### Issue description

I was looking for ... and it appears that ...
I have setup the Novu server on locally and try to create subscriber using "await novu.subscribers.identify"
but getting error "TypeError: Cannot read property 'emails' of undefined"

I trace the error and got baseURL as "baseURL: 'https://api.novu.co/v1'," it is a live URL I want it to point it local API URL 
API_ROOT_URL=http://localhost:3000. 

Could you please help me on that, I am stuck

Error : 
 config: {
    url: '/subscribers',
    method: 'post',
    data: '{"email":"ankita.mondal@47billion.com","firstName":"Ankita Mondal","phone":"9981182411"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'ApiKey < MY-API-KEY >',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 88
    },
    **baseURL: 'https://api.novu.co/v1',**
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },

### Context 🔦

When run locally

**Comment by ainouzgali** [comment]
Hi @deepaktomar47! Could you please add the code snippet you are doing? Please avoid publishing your api key, I edited your current message :)

Have you tried this way: 
`const novu = new Novu('API-KEY',{backendUrl:'http://localhost:3000'});`

**Comment by deepaktomar47** [comment]
Thanks,

`import { Novu } from '@novu/node';

const config = {
  backendUrl: 'http://local.novu.co:3000'
};

const novu = new Novu(process.env.NOVU_API_KEY, config);

export const notificationSubscrib = async (u) => {
  try {
    const user = {
      id: "efcfd636ef1311eda05b0242ac120003",
      email: u.email,
      firstName: u.firstName,
      lastName: "lastName",
      phone: u.phone,
      avatar: "profile_avatar",
      locale: "india",
      data: { custom1: 'customval1', custom2: 'customval2' }
    }
    await novu.subscribers.identify(user.id, {
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
      phone: user.phone,
      avatar: user.profile_avatar,
      locale: user.locale,
      data: { custom1: 'customval1', custom2: 'customval2' },
    }); 
  }
  catch (e) { 
    console.log(e);
  }
}
`

**getting error** 
(node:50240) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emails' of undefined

`(node:50240) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emails' of undefined
    at _callee2$ (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/utils/loginHelper.js:28:21)
    at tryCatch (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/utils/loginHelper.js:14:191)
    at /Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/utils/loginHelper.js:14:437
    at new Promise (<anonymous>)
    at /Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/utils/loginHelper.js:14:99
    at returnEmployeeData (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/utils/loginHelper.js:26:14)
    at _callee$ (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/routes/routes.js:23:28)
    at tryCatch (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/routes/routes.js:41:191)
    at /Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/src/data/routes/routes.js:41:437
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:50240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Error Object

`Error: Request failed with status code 400
    at createError (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/apple/Documents/projects/kestrel/timesheet-tool-backend-server/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: '/subscribers',
    method: 'post',
    data: '{"subscriberId":"efcfd636ef1311eda05b0242ac120003","email":"ankita.mondal@47billion.com","firstName":"Ankita Mondal","lastName":"lastName","phone":"9981182411","locale":"india","data":{"custom1":"customval1","custom2":"customval2"}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'ApiKey 85067d3f1cc300ae0bc2bd675794fe60',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 232
    },
    baseURL: 'http://local.novu.co:3000/v1',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },`

**Comment by jainpawan21** [comment]
Hi @deepaktomar47 
In case you are self hosting in any cloud server, you need to replace localhost with your server ip in `.env` file and use `backendUrl` as `http://<YOUR_SERVER_API>:3000`
If you are just running in local machine, use `backendUrl` value as `http://localhost:3000`

**Comment by deepaktomar47** [comment]
Thanks @jainpawan21,

I setup on local using docker. and it is running 

<img width="1201" alt="image" src="https://github.com/novuhq/novu/assets/9604431/6c0afae5-a968-4f7d-90a3-46469095e5c1">

**Error**

Every time this error come I tried many times with different ways.
**(node:90620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emails' of undefined**

![image](https://github.com/novuhq/novu/assets/9604431/8b6c8568-f4e7-4bc1-af44-eac09b932e7d)

**Error Object**

![image](https://github.com/novuhq/novu/assets/9604431/84129ae2-6db2-433d-9cea-4af5b71fc892)


I checked baseUrl are changed 
**baseURL: 'http://localhost:3000/v1',**


`Error: Request failed with status code 400
    at createError (/Users/apple/Documents/projects/kestrel/Kestrel_Backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/apple/Documents/projects/kestrel/Kestrel_Backend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/apple/Documents/projects/kestrel/Kestrel_Backend/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: '/subscribers',
    method: 'post',
    data: '{"subscriberId":"123","lastName":"lastName","locale":"india","data":{"custom1":"customval1","custom2":"customval2"}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'ApiKey 85067d3f1cc300ae0bc2bd675794fe60',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 116
    },
    baseURL: 'http://localhost:3000/v1',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  `
  same issue I am facing on deploying the Novu server on my Cloud.
  
  Please guide me where am i making mistake

**Comment by deepaktomar47** [comment]
Issue fixed
