### ISSUE TITLE
🐛 Bug Report: dev container does not start

### ISSUE THREAD

**Issue by collimarco** [novuhq/novu#4238]
### 📜 Description

When you try to start the dev container in VS Code you get an error.

### 👟 Reproduction steps

Open the novu project in VS Code 1.82 on MacOS Sonoma  and you get an error when you click "dev container open folder in container".

### 👍 Expected behavior

The container is started successfully.

### 👎 Actual Behavior with Screenshots

Error:

```
...
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.49: 16.8 MB/16.8 MB, done
Packages: +4754
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /workspace/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 ENOENT  ENOENT: no such file or directory, copyfile '/workspace/.pnpm-store/v3/files/f4/f9b05da82750a1016319fa3a8c4f80ed691235fc6a16d4b971ba5cc47ac1bdd71e9e2df7d8b65155b6a467b81e4d03c18e24ab8a2b56dbeef7294b73110a99' -> '/workspace/node_modules/.pnpm/@faker-js+faker@6.3.1/node_modules/@faker-js/_tmp_258_208fb56a3359876167c00c0b30617b7e/dist/types/locales/el/company/adjective.d.ts'

pnpm: ENOENT: no such file or directory, copyfile '/workspace/.pnpm-store/v3/files/f4/f9b05da82750a1016319fa3a8c4f80ed691235fc6a16d4b971ba5cc47ac1bdd71e9e2df7d8b65155b6a467b81e4d03c18e24ab8a2b56dbeef7294b73110a99' -> '/workspace/node_modules/.pnpm/@faker-js+faker@6.3.1/node_modules/@faker-js/_tmp_258_208fb56a3359876167c00c0b30617b7e/dist/types/locales/el/company/adjective.d.ts'
Progress: resolved 4659, reused 0, downloaded 4560, added 243
[655045 ms] onCreateCommand failed with exit code 1. Skipping any further user-provided commands.
[655049 ms] Error: Command failed: /bin/sh -c pnpm install && npm run setup:project
[655050 ms]     at TY (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:235:130)
[655050 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[655050 ms]     at async Ml (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:227:4393)
[655050 ms]     at async Sl (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:227:3738)
[655050 ms]     at async kl (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:227:2745)
[655050 ms]     at async stA (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:31548)
[655050 ms]     at async otA (/Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:28781)
[655059 ms] Exit code 1
[655067 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/myuser/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js run-user-commands --user-data-folder /Users/myuser/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-0a9c3141-a2cb-4d3d-bb66-30e2e7f9b3c31696065665782 --workspace-folder /Users/myuser/Desktop/novu --id-label devcontainer.local_folder=/Users/myuser/Desktop/novu --id-label devcontainer.config_file=/Users/myuser/Desktop/novu/.devcontainer/devcontainer.json --container-id 8d879bbf249044870684d98fbfb0aa07bd378c7cda7afc3925b62a283662239b --log-level debug --log-format json --config /Users/myuser/Desktop/novu/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --skip-non-blocking-commands true --prebuild false --stop-for-personalization true --remote-env REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-75ef0209-d770-45b9-b458-f5846ed3b520.sock --remote-env SSH_AUTH_SOCK=/tmp/vscode-ssh-auth-12cd-45b9-b358-f846nd5b521.sock --remote-env DISPLAY=:0 --remote-env REMOTE_CONTAINERS_DISPLAY_SOCK=/tmp/.X11-unix/X0 --remote-env REMOTE_CONTAINERS=true --mount-workspace-git-root true --dotfiles-target-path ~/dotfiles
[655067 ms] Exit code 1
```

### Novu version

0.19

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Himanshupal0001** [comment]
Any updates on the same? Also do you know how to setup dev environment for novu using  docker? Not by devcontainer!
