### ISSUE TITLE
🐛 Bug Report: TypeError: Cannot read properties of undefined (reading 'child')

### ISSUE THREAD

**Issue by dmgarland** [novuhq/novu#4838]
### 📜 Description

Seeing lots of these errors in our workers processing digests, and I see this in the stack trace for the job.

Worker log

`{
    "level": 50,
    "time": 1699008800882,
    "pid": 17,
    "serviceName": "@novu/worker",
    "serviceVersion": "0.17.1",
    "platform": "Docker",
    "tenant": "OS",
    "context": "WorkflowQueueService",
    "msg": "Failed to run the job 65437fa0b9c1e45d5c68e928 during worker processing"
}`

In the job in the Mongo database, I see this stack trace

```
error: {
      stack: "TypeError: Cannot read properties of undefined (reading 'child')\n" +
        '    at PinoLogger.assign (/usr/src/app/node_modules/.pnpm/nestjs-pino@3.1.2_g2cqd4mgcg63o5mvxc7l66lzja/node_modules/nestjs-pino/PinoLogger.js:106:37)\n' +
        '    at RunJob.<anonymous> (/usr/src/app/apps/worker/dist/webpack:/@novu/worker/src/app/workflow/usecases/run-job/run-job.usecase.ts:33:18)\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at fulfilled (/usr/src/app/apps/worker/dist/main.js:1856:58)\n' +
        '    at runMicrotasks (<anonymous>)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
      message: "Cannot read properties of undefined (reading 'child')"
    }
```

Any ideas on what might be the problem?

### 👟 Reproduction steps

This is part of the worker log

### 👍 Expected behavior

It should digest properly and send notifications

### 👎 Actual Behavior with Screenshots

error (see above)

### Novu version

0.17.1 

### 📃 Provide any additional context for the Bug.

Asked in discord #support no response yet

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nick2432** [comment]
can i work on this?
